### ISSUE TITLE
TODO list for stable version 稳定版发布前需要调整的事项

### ISSUE THREAD

**Issue by Nxer** [Nxer/Twist-Space-Technology-Mod#460]
- [x] 模块仓室的新的材质 Textures for modular hatches
 - [x] 降低普通执行核心模块造价 Buff normal execution core recipe -> cheaper
 - [x] 降低大型中子振荡器的造价 Buff Large Neutron Oscillator recipe -> cheaper
 - [x] 提高超维度物质等离子锻炉原型机MK2的造价 Nerf DTPF prototype MK2 recipe -> more expensive
 - [x] 提高速度控制模块的造价 Nerf Speed Controller Module recipe -> more expensive
 - [x] 提高无损超频控制模块的造价 Nerf Perfect Overclock Controller Module recipe -> more expensive
